### ISSUE TITLE
[Main] ERROR ThreadManager - The Steam Rate Limit has been reached. Please try again in a few minutes.

### ISSUE THREAD

**Issue by caiovrcombat** [Marc3842h/Titan#138] opened 2019-01-20 17:50 UTC
## Description

After 12 hours, I try to send the compliments, but it is giving this error, which the bots did not send. I have 350 bots and I can never use them, when I try only a few work.

## Reproduction Steps

N/A

## Errors

```bash
[Main] ERROR ThreadManager - The Steam Rate Limit has been reached. Please try again in a few minutes.
```

## System Information

**Operating System**: Windows 10
**Titan version**: 1.6.1

**Comment by sfoult17** [comment] 2019-01-20 18:36
Same. It's very anoying

**Comment by TheRhanderson** [comment] 2019-01-20 20:50
1. Split your accounts from 25 into 25.
2. Profit!

Btw I left a comment on your profile... check it out there ;)

**Comment by Marc3842h** [comment] 2019-01-21 16:55
Duplicate of #126. The way @Silentshadow83 proposes a workaround will be implemented into Titan soon-ish.

**Closed** 2019-01-21 16:56 UTC
Labels: platform: windows, status: duplicate
