### ISSUE TITLE
cant really report/commend bot

### ISSUE THREAD

**Issue by ra1N1336** [Marc3842h/Titan#8] opened 2017-06-08 03:19 UTC
this happens with both email/2fa accounts
what appears in the console after i enter the code
https://pastebin.com/XjCBSKNH

and then nothing happens
then, if i press button to report/commend again
https://pastebin.com/N2JahGNk

**Comment by Marc3842h** [comment] 2017-06-08 10:19
Are you using the latest release or did you compile from the source? Operating System?

**Comment by ra1N1336** [comment] 2017-06-09 09:02
compiled version, windows 7

**Comment by ra1N1336** [comment] 2017-06-09 09:06
gonna try to download latest release

**Comment by Marc3842h** [comment] 2017-06-09 10:42
Are there any sentry files in the `sentries` directory? Does the `sentries` directory even exist?

**Comment by ra1N1336** [comment] 2017-06-10 02:57
folder exists, but no sentry files in it

**Comment by Marc3842h** [comment] 2017-06-10 08:25
Could you use the Shared Secret Method as workaround for now? I'll investigate this.

**Comment by ra1N1336** [comment] 2017-06-10 13:44
now it just crashes when i press the button

**Comment by Marc3842h** [comment] 2017-06-10 13:45
That shouldn't happen. Can you give me a error log?

**Comment by ra1N1336** [comment] 2017-06-10 14:57
can't provide error log since after i press the button, titan freezes and stops logging, then crashes with log in console that i can't copy fully (well, i can screenshot only last strings in log)
also i tried to compile titan again, but in another folder, and i got this
![image](https://user-images.githubusercontent.com/22330838/27003802-27b4f208-4e06-11e7-8cdc-4003e2a05482.png)

**Comment by Marc3842h** [comment] 2017-06-10 15:00
Look like there is a bug in the Cake build script. I'll look into it. Also, is it possible that you can copy the log, maybe write all the log directly into a file (atleast on Linux, that is possible with > operator)? I'd appreciate that.

**Comment by ra1N1336** [comment] 2017-06-10 15:43
sorry for the wait
https://pastebin.com/AAtLKy62
i think thats because of my system's language

**Comment by Marc3842h** [comment] 2017-06-10 15:45
Did you input something into the Match ID Box?

**Comment by ra1N1336** [comment] 2017-06-10 15:49
no, but with it i also get the same crash, same goes for commends

**Comment by Marc3842h** [comment] 2017-06-10 15:56
The exception _should_ be fixed with commit b1a1529. Please try again with the latest source.

**Comment by ra1N1336** [comment] 2017-06-10 16:07
still crashes

**Comment by Marc3842h** [comment] 2017-06-10 16:12
Yea I fixed the wrong class (lol). Fixed with 4f1ec3c, try again please.

**Comment by ra1N1336** [comment] 2017-06-10 16:17
still crashes :(

**Comment by Marc3842h** [comment] 2017-06-10 16:26
What did you input in the SteamID field?

**Comment by ra1N1336** [comment] 2017-06-10 16:38
my second account's steamid

**Comment by Marc3842h** [comment] 2017-06-10 16:41
As actual SteamID like `STEAM_0:0:131983088`?

**Comment by ra1N1336** [comment] 2017-06-10 16:47
yea

**Comment by Marc3842h** [comment] 2017-06-10 16:50
With the recent changes in the source, the error should have changed from origins by a few lines. Can you pleas resend the error?

**Comment by ra1N1336** [comment] 2017-06-10 16:58
https://pastebin.com/PQQxWZaR

**Comment by Marc3842h** [comment] 2017-06-10 17:00
Did you input a valid Steam Web API key?

**Comment by ra1N1336** [comment] 2017-06-10 17:09
yes
but now i decided to generate key from another account and it doesnt crash
now i am back to report/commend botting problem
after entering the code it does nothing and after pressing the button again it begins to connect, disconnect and then repeat that

**Comment by Marc3842h** [comment] 2017-06-10 17:19
This issue is known and has been reported in #3. I thought I fixed it, but it doesn't look like that. 

The user that reported the issue suggested as workaround to generate the `sentry` file(s) on a Linux Virtual Machine (where it works for some odd reason) and move them to your actual Windows device and input the valid Shared Secret into the accounts.json for Mobile Authentification Guides. 

Issue will be investigated, but won't be highest priority.

**Comment by Marc3842h** [comment] 2017-06-12 20:28
I'm able to reproduce this issue on my Windows 10 Virtual Machine using a Steam Guard protected account. 

A fix is on its way.

**Comment by Dimitriblyater** [comment] 2017-06-21 16:15
is this fixed yet?

**Comment by Marc3842h** [comment] 2017-06-22 17:52
@Dimitriblyater I'm actually giving the new UI a higher priority simply because of the fact that Titan requires a functional UI. This issue will be fixed as soon, but currently there is no ETA available.

**Closed** 2017-09-18 11:14 UTC
Labels: platform: windows, status: reproduceable, type: bug
