### ISSUE TITLE
Commend don't work

### ISSUE THREAD

**Issue by BoberMod** [Marc3842h/Titan#11] opened 2017-06-11 15:02 UTC
Log: https://pastebin.com/BxWG3gux
Compiled from the source, win 10 x64.
I used 1 account for commend test.

Comment: the API key isn't saved to the file.

**Comment by Marc3842h** [comment] 2017-06-11 15:04
Duplicate of #8, please see issue there for more information.

**Closed by Marc3842h** 2017-06-11 15:04 UTC
Labels: platform: windows, status: duplicate, type: bug
